<?php
if ( ! defined( 'ABSPATH' ) ) {
	exit; // Exit if accessed directly
}

/**
 * WC_Admin class.
 */
class RK_page_contents {

	/**
	 * Constructor.
	 */
	public function __construct() {	
		$action_method=(isset($_REQUEST['action_method']))?$_REQUEST['action_method']:'output';
		$this->$action_method();
	}
	
	
	
	private function upload(){
			if ( ! function_exists( 'wp_handle_upload' ) ) {
				require_once( ABSPATH . 'wp-admin/includes/file.php' );
			}
			$uploadedfile = $_FILES['file'];
			$upload_overrides = array( 'test_form' => false );
			$movefile = wp_handle_upload( $uploadedfile, $upload_overrides );
			if ( $movefile && ! isset( $movefile['error'] ) ) {
				echo "File is valid, and was successfully uploaded.\n";
				var_dump( $movefile );
			} else {
				/**
				 * Error generated by _wp_handle_upload()
				 * @see _wp_handle_upload() in wp-admin/includes/file.php
				 */
				echo $movefile['error'];
			}
	}
	
	
	public function output(){
		?>
			
		<div class="wrap rk_plugin">
			<div class="bs-example">
			<ul class="nav nav-tabs">
				<li class="active"><a data-toggle="tab" href="#sectionA"><h2>WooCommerce Import Export Plugin</h2></a></li>
				<!--li><a data-toggle="tab" href="#sectionB">Section B</a></li-->
				
			</ul>
			<div class="tab-content">
		
			<div id="sectionA" class="tab-pane fade in active">
				

				<div class="divider"></div>
<div class="panel-group" id="accordion">
  <div class="panel panel-default">
    <div class="panel-heading">
      <h4 class="panel-title">
        <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion" href="#collapseOne">
         Info
        </a>
      </h4>
    </div>
    <div id="collapseOne" class="panel-collapse collapse in">
      <div class="panel-body">
        <!-- contains goes here -->
      </div>
    </div>
  </div>
  <div class="panel panel-default">
    <div class="panel-heading">
      <h4 class="panel-title">
        <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion" href="#collapseTwo">
          Product Import
        </a>
      </h4>
    </div>
    <div id="collapseTwo" class="panel-collapse collapse">
      <div class="panel-body">
      <div class="info file_info"></div>
<?php
//upload form
$this->do_action_upload_form();
?>   

		 
			  
			  
		  
		  
      </div>
    </div>
  </div>
  <div class="panel panel-default">
    <div class="panel-heading">
      <h4 class="panel-title">
        <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion" href="#collapseThree">
         Export
        </a>
      </h4>
    </div>
    <div id="collapseThree" class="panel-collapse collapse">
      <div class="panel-body">
		  <h3>Coming....fy!</h3>
      </div>
    </div>
  </div>
</div>
			</div>
				
				
				
				
				
				
		</div>
		</div>
			
	<?php
		
		
	}
	
	
	
	


function do_action_upload_form()
{
    
if(function_exists( 'wp_enqueue_media' )){
    wp_enqueue_media();
}else{
    wp_enqueue_style('thickbox');
    wp_enqueue_script('media-upload');
    wp_enqueue_script('thickbox');
}

?>

				


  <!--i class="fa fa-file-excel-o fa-6"></i -->
  <div class="container-fluid">
	  <h3 class="h3"><label>SELECT FILE TO IMPORT</label></h3>
	  <input class="header_logo_url input-lg" type="text" name="header_logo" size="60" value=""><br><br>
<a href="#" class="rk_upload_file btn btn-info btn-lg" role="button">CHOOSE FILE</a>

<a href="#" class="rk_import_btn btn btn-info btn-lg " role="button" style="background-color: #000000;">IMPORT</a>

</div>



<script type="text/javascript">
var ajaxurl = "<?php  echo admin_url('admin-ajax.php')."?page=rk-admin-dashboard&rk_action=upload"; ?>";
</script>
     
<?php



}	
	
	
	
	
	
	
	
	
}

new RK_page_contents();
?>

